version: '3'
services:
  bitbucket:
    image: "atlassian/bitbucket-server:7.5-ubuntu-jdk8"
    container_name: bitbucket
    hostname: bitbucket
    restart: always
    environment:
      BITBUCKET_HOME: /var/atlassian/application-data/bitbucket/
      JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
      ATL_TOMCAT_SCHEME: 'https'
      ATL_TOMCAT_SECURE: 'true'
      ATL_PROXY_PORT: '443'
      ATL_PROXY_NAME: 'bit.ronix.ir'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m

    volumes:
      - bitbucket-Data:/var/atlassian/application-data/bitbucket
      - ./crack/atlassian-agent-new.jar:/atlassian-agent.jar:ro
    networks:
      ronix-net:
       aliases:
        - bit
    
  db:
    image: postgres:9.6
    container_name: bitbucket-database
    hostname: bitbucket-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: '!2VfGXK]B_QMR5HR'
      POSTGRES_USER: bitbucket
      POSTGRES_DB: bitbucket
    volumes:
      - bitbucketDbVolume:/var/lib/postgresql/data
    networks:
      ronix-net:
       aliases:
        - bit-db

#  nginx:
#    restart: always
#    image: nginx:latest
#    container_name: nginx
#    hostname: nginx
#    networks:
#      - ronix-net
#    volumes:
#     - ./nginx:/etc/nginx/conf.d:ro
#     - ./ssl:/etc/nginx/ssl:ro
#    ports:
#     - 80:80
#     - 443:443      

volumes:
 bitbucket-Data:
   name: bitbucket-Data
 bitbucketDbVolume:
   name: bitbucketDbVolume


networks:
  ronix-net:
    external: true



