version: "3.4"
services:
  jira-software:
    image: atlassian/jira-software:8.22.2
    restart: always
    container_name: jira-software
    hostname: jira-software
    environment:      
      ATL_DB_DRIVER: 'org.postgresql.Driver'
      ATL_DB_TYPE: 'postgres72'
      ATL_JDBC_URL: 'jdbc:postgresql://db-jira:5432/jira'
      ATL_JDBC_USER: 'jira'
      ATL_JDBC_PASSWORD: 'Nz-!M(8`tCSTT:kc^7c$w79^t'
      ATL_TOMCAT_SCHEME: 'https'
      ATL_TOMCAT_SECURE: 'true'
      ATL_PROXY_PORT: '443'
      ATL_PROXY_NAME: 'jira.ronix.ir'
      JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m

    volumes:
      - jira-vol:/var/atlassian/application-data/jira
      - ./crack/atlassian-agent-new.jar:/atlassian-agent.jar:ro
    networks:
      ronix-net:
       aliases:
        - jira
#    ports:
#      - 8080:8080

  postgressql-jira:
    image: postgres
    restart: always
    container_name: postgressql-jira
    hostname: postgressql-jira
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: 'Nz-!M(8`tCSTT:kc^7c$w79^t'
    volumes:
      - postgresql-data-jira:/var/lib/postgresql/data
    networks:
      ronix-net:
       aliases:
        - db-jira

  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    networks:
      - ronix-net
    volumes:
     - ./nginx/etc/nginx/conf.d:ro
     - ./ssl:/etc/nginx/ssl:ro
    ports:
     - 80:80
     - 443:443      


networks:
  ronix-net:
    external: true
volumes:
  postgresql-data-jira:
    name: postgresql-data-jira
  jira-vol:
    name: jira-vol

